
var data=[
    {
        data:[
            {
                "name":"巴厘岛阿雅娜水疗度假酒店",
                "title":"阿雅娜度假村的宏伟建筑耸立在峭壁之上，从这里可俯瞰白色的沙滩和绿宝石样平静的印度洋。",
                "packageId":7010,
                "imageUrl":"http://images.asiatravel.com/Hotel/7010/Pool.jpg",
                "destCityName":"巴厘岛",
                "price":1402
            },
            {
                "name":"巴厘岛宝格丽度假村",
                "title":"巴厘岛宝格丽度假村坐落在美丽的金巴兰湾，由世界知名建筑设计师-Antonio Citterio倾力打造，一栋栋顺着断崖地势兴建的私密别墅，让您可以直接从私人别墅阳台一览印度洋绚烂的夕阳景致！",
                "packageId":17737,
                "imageUrl":"http://images.asiatravel.com/Hotel/17737/Ocean-Cliff-Villa-Plunge-Pool-(2).jpg?_ga=1.165755006.1113472130.1486535066",
                "destCityName":"巴厘岛",
                "price":4162
            },

            {
                "name":"巴厘岛悦榕庄昂格桑酒店",
                "title":"悦榕庄昂格桑酒店距离金巴兰湾有10分钟车程，提供4个餐饮场所和一个无边游泳池，可欣赏印度洋的景色。 ",
                "packageId":23895,
                "imageUrl":"http://images.asiatravel.com/Hotel/23895/Ju-Ma-Na-Bar-Exterior.jpg.jpg?_ga=1.133437774.1113472130.1486535066",
                "destCityName":"巴厘岛",
                "price":4415
            },
            {
                "name":"芽庄安林宁帆湾别墅",
                "title":"安林宁湾海湾不同于你以往去过的任何地方。这里有开阔的视野，椰子树和茅草搭成的高大的拱形屋顶，让新鲜清爽的空气在房间内自由流通，丝毫没有炎热的感觉。 ",
                "packageId":16756,
                "imageUrl":"http://images.asiatravel.com/Hotel/16756/Beach.jpg?_ga=1.122221899.1113472130.1486535066",
                "destCityName":"芽庄",
                "price":2211
            },
            {
                "name":"芽庄珍珠豪华酒店",
                "title":"芽庄湾素来享有全球海滩之最之美誉，曾被评为全世界最美丽的三十个海湾之一，而芽庄珍珠豪华酒店则将单独建在美丽迷人的芽庄湾上风景最为动人优美的岛屿——Hon Tre岛上，周围风景如画，美不胜收。",
                "packageId":9860,
                "imageUrl":"http://images.asiatravel.com/Hotel/9860/9860pool.jpg?_ga=1.130694351.1113472130.1486535066",
                "destCityName":"芽庄",
                "price":2295
            },
            {
                "name":"普吉岛卡踏参尼海滩度假酒店",
                "title":"卡他泰尼普吉海滩度假村位于卡他山海滩这个华贵的天堂里，度假村以其宁静和舒适的环境著称。酒店周围白色海滩和天然的热带风景相映成趣，构成了无与伦比的平静、安详的美丽画面。",
                "packageId":652,
                "imageUrl":"http://images.asiatravel.com/Hotel/652/652-Katathani-Phuket-Wedding1.jpg?_ga=1.163312892.1113472130.1486535066",
                "destCityName":"普吉岛",
                "price":1497
            },
            {
                "name":"普吉岛悦榕庄酒店",
                "title":"悦榕庄位于邦道湾（Bang Tao Bay），由多座亚洲式别墅组成，以传统泰国风格布置的别墅，每个都带私家花园，大号床，露天温泉/淋浴。度假村共有109座别墅。设施齐全、活动丰富。",
                "packageId":476,
                "imageUrl":"http://images.asiatravel.com/Hotel/476/476_Banyan_Tree_Phuket_Resort.jpg?_ga=1.129234124.1113472130.1486535066",
                "destCityName":"普吉岛",
                "price":2799
            }

        ]
    },
    {
        data:[

            {
                "name":"曼谷暹罗凯宾斯基饭店",
                "title":"酒店距离Siam Paragon购物中心仅几步之遥，从酒店穿过Siam Paragon购物中心即可轻松前往Siam BTS轻轨站",
                "packageId":8386,
                "imageUrl":"http://images.asiatravel.com/Hotel/8386/8386_siam_kempinski_hotel_bangkok_fronthotel.jpg",
                "destCityName":"曼谷",
                "price":1803
            },
            {
                "name":"曼谷东方宾馆",
                "title":"酒店地理位置优越，四周环绕着郁郁葱葱的树木，在曼谷的商业和使馆区的中心",
                "packageId":10349,
                "imageUrl":"http://images.asiatravel.com/Hotel/10349/10349-Oriental-Residence-Bangkok.jpg?_ga=1.12155956.1657715909.1461726004",
                "destCityName":"曼谷",
                "price":849
            },
            {
                "name":"曼谷斯瓦特尔酒店",
                "title":"酒店坐落在巴吞旺地区，紧临活力四射的曼谷市区。旅客可在临近的苏安帕凯德宮殿博物馆欣赏工艺品的展出，或在巴吞南市场购物",
                "packageId":9738,
                "imageUrl":"http://images.asiatravel.com/Hotel/9738/9738_Sivatel_Bangkok_Hotel_Swimming_Pool_01.jpg?_ga=1.45758500.1657715909.1461726004",
                "destCityName":"曼谷",
                "price":1102
            },
            {
                "name":"玛杜兹酒店",
                "title":"酒店位于曼谷素坤逸路，靠近阿根廷大使馆，鲁皮尼公园，水门市场，同时也靠近21号航站楼购物商场和印度使馆",
                "packageId":10295,
                "imageUrl":"http://images.asiatravel.com/Hotel/10295/10295_maduzi_hotel_External02.jpg?_ga=1.75053074.1657715909.1461726004",
                "destCityName":"曼谷",
                "price":1303
            },
            {
                "name":"曼谷厄巴朗顺酒店",
                "title":"这家家庭友好的公寓酒店位于曼谷市中心，靠近美国使馆、尚泰祁隆购物广场、尚泰使馆商场",
                "packageId":2344,
                "imageUrl":"http://images.asiatravel.com/Hotel/2344/2344-Swimming-Pool.jpg?_ga=1.245455108.1657715909.1461726004",
                "destCityName":"曼谷",
                "price":411
            }
        ]
    },
    {
        data:[
            {
                "name":"清迈平那科酒店",
                "title":"酒店是杰出豪华酒店，为旅客提供尊贵的“家庭服务”。所有的工作人员都训练有素，以确保它们具有高水准的能力和技巧，以及出色的服务意识，让您的假期更加愉快。",
                "packageId":20041,
                "imageUrl":"http://images.asiatravel.com/Hotel/20041/20041-Deluxe2.jpg?_ga=1.133297614.1113472130.1486535066",
                "destCityName":"清迈",
                "price":240
            },
            {
                "name":"清迈普山法度假酒店",
                "title":"这是一家位于湄登区神奇的精品度假酒店，该度假村是由当地居民和工匠建造，设计灵感来自传统的泰国北部兰纳风格。从度假村可眺望到稻田和周围神秘的景色。度假村视觉上封装了泰国北部的传统田园魅力，同时提供热情的泰式款待和现代化的设施。",
                "packageId":19891,
                "imageUrl":"http://images.asiatravel.com/Hotel/19891/19891-Phusanfah-Resort.jpg",
                "destCityName":"清迈",
                "price":496
            },
            {
                "name":"阿莫清迈度假酒店",
                "title":"阿莫清迈度假酒店是一家3星级酒店，距离市中心仅15公里，酒店共有14间客房。酒店的娱乐设施包括按摩、花园。此外酒店的服务包括咖啡店、洗衣服务、行政楼层、客房服务、旅游服务。",
                "packageId":14869,
                "imageUrl":"http://images.asiatravel.com/Hotel/14869/14869_Is_Am_O_Chiang_mai_Resort.jpg",
                "destCityName":"清迈",
                "price":200
            },
            {
                "name":"清迈古镇梧桐酒店 ",
                "title":"清迈古镇梧桐酒店位于步行街，步行五分钟即可到塔佩门，从酒店可以很方便地到达夜市街、购物中心，驾车仅需10分钟即可到达机场。酒店位于市中心，邻近三王纪念碑、契迪龙寺、帕辛寺以及其它众多的庙宇，且邻近兰纳王国建筑中心。",
                "packageId":6670,
                "imageUrl":"http://images.asiatravel.com/Hotel/6670/6670-Parasol-Inn.jpg",
                "destCityName":"清迈",
                "price":283
            },
            {
                "name":"清迈丁奇之家酒店 ",
                "title":"丁奇之家酒店距离深受欢迎的Nimman 路和清迈动物园有5分钟步行路程,是一个距离清迈市中心只有4公里的舒适酒店，距离清迈国际机场有10分钟车程。",
                "packageId":16007,
                "imageUrl":"http://images.asiatravel.com/Hotel/16007/16007-Attraction-02.jpg?_ga=1.125507658.1113472130.1486535066",
                "destCityName":"清迈",
                "price":99
            },
            {
                "name":"清迈小雅酒店",
                "title":"酒店位于华欣市中心，Nareaddhumri Road，邻近海滩。仅需步行路程即可到达夜间购物中心，距离Warorot市场有3分钟的步行路程。",
                "packageId":7313,
                "imageUrl":"http://images.asiatravel.com/Hotel/7313/7313_the_small_hotel_chiang_mai_PlusPetit02.jpg?_ga=1.66663662.1113472130.1486535066",
                "destCityName":"清迈",
                "price":218
            }
        ]
    },
    {
        data:[

            {
                "name":"曼谷暹罗设计酒店",
                "title":"豪华客房就位于曼谷的闹市中，设计独特，有着其本的理念，是一个理想的休息度假地。高雅的室内设计，一个极具创造力的空间，现代舒适的住宿环境，高品位的生活方式",
                "packageId":5106,
                "imageUrl":"http://images.asiatravel.com/Hotel/5106/5106_Siam_At_Siam_Design_Hotel_And_Spa_Lobby02.jpg?_ga=1.250754182.1657715909.1461726004",
                "destCityName":"曼谷",
                "price":582
            },
            {
                "name":"萨拉拉坦纳可心曼谷酒店",
                "title":"酒店设有带现代室内装潢和连接浴室的舒适客房。酒店各处均覆盖免费无线网络连接",
                "packageId":14884,
                "imageUrl":"http://images.asiatravel.com/Hotel/14884/14884_Sala_Rattanakosin_Bangkok_Restaurant_6.jpg?_ga=1.75135122.1657715909.1461726004",
                "destCityName":"曼谷",
                "price":550
            },
            {
                "name":"雅乐轩曼谷素坤逸 11 号酒店",
                "title":"您可以到这家餐厅或咖啡馆享用一顿美餐。也可以呆在房间里，享受酒店的24 小时客房送餐服务。欢迎光临酒吧/酒廊或池畔酒吧，点一杯喜欢的饮品，放松一下",
                "packageId":4001929,
                "imageUrl":"http://media.expedia.com/hotels/5000000/4430000/4425200/4425151/4425151_195_b.jpg",
                "destCityName":"曼谷",
                "price":492
            },
            {
                "name":"清迈艺术画廊尼曼酒店",
                "title":"房间由艺术家独特设计，拥有个性化的服务，酒店的客人可以欣赏遍布酒店的来自当地艺术家的艺术作品，酒店大厅出售现代收藏艺术品",
                "packageId":19327,
                "imageUrl":"http://images.asiatravel.com/Hotel/19327/19327-Art-Gallery-Connecting3.jpg?_ga=1.255351176.1657715909.1461726004",
                "destCityName":"清迈",
                "price":529
            },
            {
                "name":"W曼谷酒店",
                "title":"你可以在W酒店标志的床上做着美梦，或懒散的裹着毛绒浴袍，舒适享受国家的最先进的娱乐",
                "packageId":13887,
                "imageUrl":"http://images.asiatravel.com/Hotel/13887/13887_W_Bangkok_exterior.jpg",
                "destCityName":"曼谷",
                "price":1026
            }
        ]
    }
]