<?php
defined('BASEPATH') OR exit('No direct script access allowed');
//include_once( BASEPATH . '/helpers/form_helper'.EXT
// ------------------------------------------------------------------------
if ( ! function_exists('get_country'))
{
  function  get_country(){
    $list= array(
        array(
            "countryCode" => "DZ",
            "chineseName" => "阿尔及利亚",
            "englishName" => "Algeria",
            "nativeName" => "Middle East",
            "nationalityCode" => "DZA",
            "phoneCode" => "213",
            "fullPinYin" => "AErJiLiYa",
            "simplePinYin" => "AEJLY",
            "firstPinYin" => "A",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "EG",
            "chineseName" => "埃及",
            "englishName" => "Egypt",
            "nativeName" => "Africa",
            "nationalityCode" => "EGY",
            "phoneCode" => "20",
            "fullPinYin" => "AiJi",
            "simplePinYin" => "AJ",
            "firstPinYin" => "A",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "LY",
            "chineseName" => "阿拉伯利比亚民众国",
            "englishName" => "Libyan Arab Jamahiriya",
            "nativeName" => "Middle East",
            "nationalityCode" => "LBY",
            "phoneCode" => "218",
            "fullPinYin" => "ALaBaiLiBiYaMinZhongGuo",
            "simplePinYin" => "ALBLBYMZG",
            "firstPinYin" => "A",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "AO",
            "chineseName" => "安哥拉",
            "englishName" => "Angola",
            "nativeName" => "Africa",
            "nationalityCode" => "AGO",
            "phoneCode" => "244",
            "fullPinYin" => "AnGeLa",
            "simplePinYin" => "AGL",
            "firstPinYin" => "A",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "ET",
            "chineseName" => "埃塞俄比亚",
            "englishName" => "Ethiopia",
            "nativeName" => "Africa",
            "nationalityCode" => "ETH",
            "phoneCode" => "251",
            "fullPinYin" => "AiSaiEBiYa",
            "simplePinYin" => "ASEBY",
            "firstPinYin" => "A",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "AF",
            "chineseName" => "阿富汗",
            "englishName" => "Afghanistan",
            "nativeName" => "Middle East",
            "nationalityCode" => "AFG",
            "phoneCode" => "93",
            "fullPinYin" => "AFuHan",
            "simplePinYin" => "AFH",
            "firstPinYin" => "A",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "AU",
            "chineseName" => "澳大利亚",
            "englishName" => "Australia",
            "nativeName" => "Australia / New Zealand/ S W Pacific",
            "nationalityCode" => "AUS",
            "phoneCode" => "61",
            "fullPinYin" => "AoDaLiYa",
            "simplePinYin" => "ADLY",
            "firstPinYin" => "A",
            "isHot" => 1,
        ),
        array(
            "countryCode" => "MO",
            "chineseName" => "澳门特别行政区",
            "englishName" => "Macau (sar) China",
            "nativeName" => "North Asia",
            "nationalityCode" => "MAC",
            "phoneCode" => "853",
            "fullPinYin" => "AoMenTeBieHangZhengOu",
            "simplePinYin" => "AMTBHZO",
            "firstPinYin" => "A",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "AT",
            "chineseName" => "奥地利",
            "englishName" => "Austria",
            "nativeName" => "Europe",
            "nationalityCode" => "AUT",
            "phoneCode" => "43",
            "fullPinYin" => "AoDeLi",
            "simplePinYin" => "ADL",
            "firstPinYin" => "A",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "AL",
            "chineseName" => "阿尔巴尼亚",
            "englishName" => "Albania",
            "nativeName" => "Europe",
            "nationalityCode" => "ALB",
            "phoneCode" => "355",
            "fullPinYin" => "AErBaNiYa",
            "simplePinYin" => "AEBNY",
            "firstPinYin" => "A",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "AZ",
            "chineseName" => "阿塞拜疆",
            "englishName" => "Azerbaijan",
            "nativeName" => "Middle East",
            "nationalityCode" => "AZE",
            "phoneCode" => "994",
            "fullPinYin" => "ASaiBaiJiang",
            "simplePinYin" => "ASBJ",
            "firstPinYin" => "A",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "EE",
            "chineseName" => "爱沙尼亚",
            "englishName" => "Estonia",
            "nativeName" => "Europe",
            "nationalityCode" => "EST",
            "phoneCode" => "372",
            "fullPinYin" => "AiShaNiYa",
            "simplePinYin" => "ASNY",
            "firstPinYin" => "A",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "AG",
            "chineseName" => "安提瓜和巴布达，背风群岛",
            "englishName" => "Antigua and Barbuda, Leeward Islands",
            "nativeName" => "South America",
            "nationalityCode" => "ATG",
            "phoneCode" => "1268",
            "fullPinYin" => "AnDiGuaHeBaBuDa，BeiFengQunDao",
            "simplePinYin" => "ADGHBBD，BFQD",
            "firstPinYin" => "A",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "AI",
            "chineseName" => "安圭拉，背风群岛",
            "englishName" => "Anguilla, Leeward Islands",
            "nativeName" => "Others",
            "nationalityCode" => "AIA",
            "phoneCode" => "1",
            "fullPinYin" => "AnGuiLa，BeiFengQunDao",
            "simplePinYin" => "AGL，BFQD",
            "firstPinYin" => "A",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "AW",
            "chineseName" => "阿鲁巴",
            "englishName" => "Aruba",
            "nativeName" => "Others",
            "nationalityCode" => "ABW",
            "phoneCode" => "297",
            "fullPinYin" => "ALuBa",
            "simplePinYin" => "ALB",
            "firstPinYin" => "A",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "AR",
            "chineseName" => "阿根廷",
            "englishName" => "Argentina",
            "nativeName" => "South America",
            "nationalityCode" => "ARG",
            "phoneCode" => "54",
            "fullPinYin" => "AGenTing",
            "simplePinYin" => "AGT",
            "firstPinYin" => "A",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "AE",
            "chineseName" => "阿联酋",
            "englishName" => "United Arab Emirates",
            "nativeName" => "Middle East",
            "nationalityCode" => "ARE",
            "phoneCode" => "971",
            "fullPinYin" => "ALianQiu",
            "simplePinYin" => "ALQ",
            "firstPinYin" => "A",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "OM",
            "chineseName" => "阿曼",
            "englishName" => "Oman",
            "nativeName" => "Middle East",
            "nationalityCode" => "OMN",
            "phoneCode" => "968",
            "fullPinYin" => "AMan",
            "simplePinYin" => "AM",
            "firstPinYin" => "A",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "SY",
            "chineseName" => "阿拉伯叙利亚共和国",
            "englishName" => "Syrian Arab Republic",
            "nativeName" => "Middle East",
            "nationalityCode" => "SYR",
            "phoneCode" => "963",
            "fullPinYin" => "ALaBaiXuLiYaGongHeGuo",
            "simplePinYin" => "ALBXLYGHG",
            "firstPinYin" => "A",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "BW",
            "chineseName" => "博茨瓦纳",
            "englishName" => "Botswana",
            "nativeName" => "Africa",
            "nationalityCode" => "BWA",
            "phoneCode" => "267",
            "fullPinYin" => "BoCiWaNa",
            "simplePinYin" => "BCWN",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "BF",
            "chineseName" => "布基纳法索",
            "englishName" => "Burkina Faso",
            "nativeName" => "Africa",
            "nationalityCode" => "BFA",
            "phoneCode" => "226",
            "fullPinYin" => "BuJiNaFaSuo",
            "simplePinYin" => "BJNFS",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "BJ",
            "chineseName" => "贝宁",
            "englishName" => "Benin",
            "nativeName" => "Africa",
            "nationalityCode" => "BEN",
            "phoneCode" => "229",
            "fullPinYin" => "BeiNing",
            "simplePinYin" => "BN",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "BI",
            "chineseName" => "布隆迪",
            "englishName" => "Burundi",
            "nativeName" => "Africa",
            "nationalityCode" => "BIF",
            "phoneCode" => "257",
            "fullPinYin" => "BuLongDi",
            "simplePinYin" => "BLD",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "MP",
            "chineseName" => "北马里亚纳群岛（不包括关岛）",
            "englishName" => "Northern Mariana Islands (except Guam)",
            "nativeName" => "Others",
            "nationalityCode" => "MNP",
            "phoneCode" => "1670",
            "fullPinYin" => "BeiMaLiYaNaQunDao（BuBaoGuaGuanDao）",
            "simplePinYin" => "BMLYNQD（BBGGD）",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "PG",
            "chineseName" => "巴布亚新几内亚",
            "englishName" => "Papua New Guinea",
            "nativeName" => "Australia / New Zealand/ S W Pacific",
            "nationalityCode" => "PNG",
            "phoneCode" => "675",
            "fullPinYin" => "BaBuYaXinJiNeiYa",
            "simplePinYin" => "BBYXJNY",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "PW",
            "chineseName" => "贝劳",
            "englishName" => "Palau",
            "nativeName" => "Australia / New Zealand/ S W Pacific",
            "nationalityCode" => "PLW",
            "phoneCode" => "680",
            "fullPinYin" => "BeiLao",
            "simplePinYin" => "BL",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "PK",
            "chineseName" => "巴基斯坦",
            "englishName" => "Pakistan",
            "nativeName" => "Middle East",
            "nationalityCode" => "PAK",
            "phoneCode" => "92",
            "fullPinYin" => "BaJiSiTan",
            "simplePinYin" => "BJST",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "BT",
            "chineseName" => "不丹",
            "englishName" => "Bhutan",
            "nativeName" => "India & Sub. Continents",
            "nationalityCode" => "BTN",
            "phoneCode" => "975",
            "fullPinYin" => "BuDan",
            "simplePinYin" => "BD",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "BE",
            "chineseName" => "比利时",
            "englishName" => "Belgium",
            "nativeName" => "Europe",
            "nationalityCode" => "BEL",
            "phoneCode" => "32",
            "fullPinYin" => "BiLiShi",
            "simplePinYin" => "BLS",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "IS",
            "chineseName" => "冰岛",
            "englishName" => "Iceland",
            "nativeName" => "Europe",
            "nationalityCode" => "ISL",
            "phoneCode" => "354",
            "fullPinYin" => "BingDao",
            "simplePinYin" => "BD",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "BA",
            "chineseName" => "波斯尼亚和黑塞哥维那",
            "englishName" => "Bosnia and Herzegovina",
            "nativeName" => "Europe",
            "nationalityCode" => "BIH",
            "phoneCode" => "387",
            "fullPinYin" => "BoSiNiYaHeHeiSaiGeWeiNa",
            "simplePinYin" => "BSNYHHSGWN",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "BG",
            "chineseName" => "保加利亚",
            "englishName" => "Bulgaria",
            "nativeName" => "Europe",
            "nationalityCode" => "BGR",
            "phoneCode" => "359",
            "fullPinYin" => "BaoJiaLiYa",
            "simplePinYin" => "BJLY",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "BY",
            "chineseName" => "白俄罗斯",
            "englishName" => "Belarus",
            "nativeName" => "Europe",
            "nationalityCode" => "BLR",
            "phoneCode" => "375",
            "fullPinYin" => "BaiELuoSi",
            "simplePinYin" => "BELS",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "PL",
            "chineseName" => "波兰",
            "englishName" => "Poland",
            "nativeName" => "Europe",
            "nationalityCode" => "POL",
            "phoneCode" => "48",
            "fullPinYin" => "BoLan",
            "simplePinYin" => "BL",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "BB",
            "chineseName" => "巴巴多斯",
            "englishName" => "Barbados",
            "nativeName" => "South America",
            "nationalityCode" => "BRB",
            "phoneCode" => "1246",
            "fullPinYin" => "BaBaDuoSi",
            "simplePinYin" => "BBDS",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "BM",
            "chineseName" => "百慕大",
            "englishName" => "Bermuda",
            "nativeName" => "South America",
            "nationalityCode" => "BMU",
            "phoneCode" => "1441",
            "fullPinYin" => "BaiMuDa",
            "simplePinYin" => "BMD",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "BS",
            "chineseName" => "巴哈马",
            "englishName" => "Bahamas",
            "nativeName" => "South America",
            "nationalityCode" => "BHS",
            "phoneCode" => "1242",
            "fullPinYin" => "BaHaMa",
            "simplePinYin" => "BHM",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "PR",
            "chineseName" => "波多黎各",
            "englishName" => "Puerto Rico",
            "nativeName" => "South America",
            "nationalityCode" => "PRI",
            "phoneCode" => "1787",
            "fullPinYin" => "BoDuoLiGe",
            "simplePinYin" => "BDLG",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "BZ",
            "chineseName" => "伯利兹",
            "englishName" => "Belize",
            "nativeName" => "South America",
            "nationalityCode" => "BLZ",
            "phoneCode" => "501",
            "fullPinYin" => "BaiLiCi",
            "simplePinYin" => "BLC",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "PA",
            "chineseName" => "巴拿马",
            "englishName" => "Panama",
            "nativeName" => "South America",
            "nationalityCode" => "PAN",
            "phoneCode" => "507",
            "fullPinYin" => "BaNaMa",
            "simplePinYin" => "BNM",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "BO",
            "chineseName" => "玻利维亚",
            "englishName" => "Bolivia",
            "nativeName" => "South America",
            "nationalityCode" => "BOL",
            "phoneCode" => "591",
            "fullPinYin" => "BoLiWeiYa",
            "simplePinYin" => "BLWY",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "PE",
            "chineseName" => "秘鲁",
            "englishName" => "Peru",
            "nativeName" => "South America",
            "nationalityCode" => "PER",
            "phoneCode" => "51",
            "fullPinYin" => "BiLu",
            "simplePinYin" => "BL",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "BR",
            "chineseName" => "巴西",
            "englishName" => "Brazil",
            "nativeName" => "South America",
            "nationalityCode" => "BRA",
            "phoneCode" => "55",
            "fullPinYin" => "BaXi",
            "simplePinYin" => "BX",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "PY",
            "chineseName" => "巴拉圭",
            "englishName" => "Paraguay",
            "nativeName" => "South America",
            "nationalityCode" => "PRY",
            "phoneCode" => "595",
            "fullPinYin" => "BaLaGui",
            "simplePinYin" => "BLG",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "BH",
            "chineseName" => "巴林",
            "englishName" => "Bahrain",
            "nativeName" => "Middle East",
            "nationalityCode" => "BHR",
            "phoneCode" => "973",
            "fullPinYin" => "BaLin",
            "simplePinYin" => "BL",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "PS",
            "chineseName" => "巴勒斯坦",
            "englishName" => "Palestine",
            "nativeName" => "Middle East",
            "nationalityCode" => "PSE",
            "phoneCode" => "970",
            "fullPinYin" => "BaLeSiTan",
            "simplePinYin" => "BLST",
            "firstPinYin" => "B",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "GQ",
            "chineseName" => "赤道几内亚",
            "englishName" => "Equatorial Guinea",
            "nativeName" => "Africa",
            "nationalityCode" => "GNQ",
            "phoneCode" => "240",
            "fullPinYin" => "ChiDaoJiNeiYa",
            "simplePinYin" => "CDJNY",
            "firstPinYin" => "C",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "KR",
            "chineseName" => "朝鲜",
            "englishName" => "Korea (South)",
            "nativeName" => "North Asia",
            "nationalityCode" => "KOR",
            "phoneCode" => "82",
            "fullPinYin" => "ChaoXian",
            "simplePinYin" => "CX",
            "firstPinYin" => "C",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "TG",
            "chineseName" => "多哥",
            "englishName" => "Togo",
            "nativeName" => "Africa",
            "nationalityCode" => "TGO",
            "phoneCode" => "228",
            "fullPinYin" => "DuoGe",
            "simplePinYin" => "DG",
            "firstPinYin" => "D",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "TJ",
            "chineseName" => "塔吉克斯坦",
            "englishName" => "Tajikistan",
            "nativeName" => "Middle East",
            "nationalityCode" => "TJK",
            "phoneCode" => "992",
            "fullPinYin" => "DaJiKeSiTan",
            "simplePinYin" => "DJKST",
            "firstPinYin" => "D",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "TL",
            "chineseName" => "东帝汶",
            "englishName" => "Timor-leste",
            "nativeName" => "Australia / New Zealand/ S W Pacific",
            "nationalityCode" => "TLS",
            "phoneCode" => "670",
            "fullPinYin" => "DongDiWen",
            "simplePinYin" => "DDW",
            "firstPinYin" => "D",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "DE",
            "chineseName" => "德国",
            "englishName" => "Germany",
            "nativeName" => "Europe",
            "nationalityCode" => "DEU",
            "phoneCode" => "49",
            "fullPinYin" => "DeGuo",
            "simplePinYin" => "DG",
            "firstPinYin" => "D",
            "isHot" => 1,
        ),
        array(
            "countryCode" => "DK",
            "chineseName" => "丹麦",
            "englishName" => "Denmark",
            "nativeName" => "Europe",
            "nationalityCode" => "DNK",
            "phoneCode" => "45",
            "fullPinYin" => "DanMai",
            "simplePinYin" => "DM",
            "firstPinYin" => "D",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "DM",
            "chineseName" => "多米尼克",
            "englishName" => "Dominica",
            "nativeName" => "South America",
            "nationalityCode" => "DMA",
            "phoneCode" => "1",
            "fullPinYin" => "DuoMiNiKe",
            "simplePinYin" => "DMNK",
            "firstPinYin" => "D",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "DO",
            "chineseName" => "多米尼加共和国",
            "englishName" => "Dominican Republic",
            "nativeName" => "South America",
            "nationalityCode" => "DOM",
            "phoneCode" => "1809",
            "fullPinYin" => "DuoMiNiJiaGongHeGuo",
            "simplePinYin" => "DMNJGHG",
            "firstPinYin" => "D",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "ER",
            "chineseName" => "厄立特里亚",
            "englishName" => "Eritrea",
            "nativeName" => "Africa",
            "nationalityCode" => "ERI",
            "phoneCode" => "291",
            "fullPinYin" => "ELiTeLiYa",
            "simplePinYin" => "ELTLY",
            "firstPinYin" => "E",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "RU",
            "chineseName" => "俄罗斯联邦",
            "englishName" => "Russian Federation",
            "nativeName" => "Europe",
            "nationalityCode" => "RUS",
            "phoneCode" => "7",
            "fullPinYin" => "ELuoSiLianBang",
            "simplePinYin" => "ELSLB",
            "firstPinYin" => "E",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "IE",
            "chineseName" => "尔兰共和国",
            "englishName" => "Ireland Republic of",
            "nativeName" => "Europe",
            "nationalityCode" => "IRL",
            "phoneCode" => "353",
            "fullPinYin" => "ErLanGongHeGuo",
            "simplePinYin" => "ELGHG",
            "firstPinYin" => "E",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "EC",
            "chineseName" => "厄瓜多尔",
            "englishName" => "Ecuador",
            "nativeName" => "South America",
            "nationalityCode" => "ECU",
            "phoneCode" => "593",
            "fullPinYin" => "EGuaDuoEr",
            "simplePinYin" => "EGDE",
            "firstPinYin" => "E",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "CV",
            "chineseName" => "佛得角",
            "englishName" => "Cape Verde",
            "nativeName" => "Africa",
            "nationalityCode" => "CPV",
            "phoneCode" => "238",
            "fullPinYin" => "FoDeJiao",
            "simplePinYin" => "FDJ",
            "firstPinYin" => "F",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "FJ",
            "chineseName" => "斐济",
            "englishName" => "Fiji",
            "nativeName" => "Australia / New Zealand/ S W Pacific",
            "nationalityCode" => "FJI",
            "phoneCode" => "679",
            "fullPinYin" => "FeiJi",
            "simplePinYin" => "FJ",
            "firstPinYin" => "F",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "PF",
            "chineseName" => "法属波利尼西亚",
            "englishName" => "French Polynesia",
            "nativeName" => "South America",
            "nationalityCode" => "PYF",
            "phoneCode" => "689",
            "fullPinYin" => "FaShuBoLiNiXiYa",
            "simplePinYin" => "FSBLNXY",
            "firstPinYin" => "F",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "PH",
            "chineseName" => "菲律宾",
            "englishName" => "Philippines",
            "nativeName" => "S.E. Asia",
            "nationalityCode" => "PHL",
            "phoneCode" => "63",
            "fullPinYin" => "FeiLvBin",
            "simplePinYin" => "FLB",
            "firstPinYin" => "F",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "FI",
            "chineseName" => "芬兰",
            "englishName" => "Finland",
            "nativeName" => "Europe",
            "nationalityCode" => "FIN",
            "phoneCode" => "358",
            "fullPinYin" => "FenLan",
            "simplePinYin" => "FL",
            "firstPinYin" => "F",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "FO",
            "chineseName" => "法罗群岛",
            "englishName" => "Faroe Islands",
            "nativeName" => "South America",
            "nationalityCode" => "FRO",
            "phoneCode" => "298",
            "fullPinYin" => "FaLuoQunDao",
            "simplePinYin" => "FLQD",
            "firstPinYin" => "F",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "FR",
            "chineseName" => "法国",
            "englishName" => "France",
            "nativeName" => "Europe",
            "nationalityCode" => "FRA",
            "phoneCode" => "33",
            "fullPinYin" => "FaGuo",
            "simplePinYin" => "FG",
            "firstPinYin" => "F",
            "isHot" => 1,
        ),
        array(
            "countryCode" => "GF",
            "chineseName" => "法属圭亚那",
            "englishName" => "French Guiana",
            "nativeName" => "South America",
            "nationalityCode" => "GUF",
            "phoneCode" => "594",
            "fullPinYin" => "FaShuGuiYaNa",
            "simplePinYin" => "FSGYN",
            "firstPinYin" => "F",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "FK",
            "chineseName" => "福克兰群岛",
            "englishName" => "Falkland Islands",
            "nativeName" => "South America",
            "nationalityCode" => "FLK",
            "phoneCode" => "500",
            "fullPinYin" => "FuKeLanQunDao",
            "simplePinYin" => "FKLQD",
            "firstPinYin" => "F",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "CD",
            "chineseName" => "刚果民主共和国",
            "englishName" => "Congo Democratic Republic of",
            "nativeName" => "Africa",
            "nationalityCode" => "COD",
            "phoneCode" => "243",
            "fullPinYin" => "GangGuoMinZhuGongHeGuo",
            "simplePinYin" => "GGMZGHG",
            "firstPinYin" => "G",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "CG",
            "chineseName" => "刚果",
            "englishName" => "Congo",
            "nativeName" => "Africa",
            "nationalityCode" => "COG",
            "phoneCode" => "242",
            "fullPinYin" => "GangGuo",
            "simplePinYin" => "GG",
            "firstPinYin" => "G",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "GM",
            "chineseName" => "冈比亚",
            "englishName" => "Gambia",
            "nativeName" => "Africa",
            "nationalityCode" => "GMB",
            "phoneCode" => "220",
            "fullPinYin" => "GangBiYa",
            "simplePinYin" => "GBY",
            "firstPinYin" => "G",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "GU",
            "chineseName" => "关岛",
            "englishName" => "Guam",
            "nativeName" => "South America",
            "nationalityCode" => "GUM",
            "phoneCode" => "1671",
            "fullPinYin" => "GuanDao",
            "simplePinYin" => "GD",
            "firstPinYin" => "G",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "GE",
            "chineseName" => "格鲁吉亚",
            "englishName" => "Georgia",
            "nativeName" => "Europe",
            "nationalityCode" => "GEO",
            "phoneCode" => "995",
            "fullPinYin" => "GeLuJiYa",
            "simplePinYin" => "GLJY",
            "firstPinYin" => "G",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "CU",
            "chineseName" => "古巴",
            "englishName" => "Cuba",
            "nativeName" => "South America",
            "nationalityCode" => "CUB",
            "phoneCode" => "53",
            "fullPinYin" => "GuBa",
            "simplePinYin" => "GB",
            "firstPinYin" => "G",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "GD",
            "chineseName" => "格林纳达，向风群岛",
            "englishName" => "Grenada, Windward Islands",
            "nativeName" => "South America",
            "nationalityCode" => "GRD",
            "phoneCode" => "1",
            "fullPinYin" => "GeLinNaDa，XiangFengQunDao",
            "simplePinYin" => "GLND，XFQD",
            "firstPinYin" => "G",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "GP",
            "chineseName" => "瓜德罗普",
            "englishName" => "Guadeloupe",
            "nativeName" => "Others",
            "nationalityCode" => "GLP",
            "phoneCode" => "590",
            "fullPinYin" => "GuaDeLuoPu",
            "simplePinYin" => "GDLP",
            "firstPinYin" => "G",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "CR",
            "chineseName" => "哥斯达黎加",
            "englishName" => "Costa Rica",
            "nativeName" => "South America",
            "nationalityCode" => "CRI",
            "phoneCode" => "506",
            "fullPinYin" => "GeSiDaLiJia",
            "simplePinYin" => "GSDLJ",
            "firstPinYin" => "G",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "CO",
            "chineseName" => "哥伦比亚",
            "englishName" => "Colombia",
            "nativeName" => "South America",
            "nationalityCode" => "COL",
            "phoneCode" => "57",
            "fullPinYin" => "GeLunBiYa",
            "simplePinYin" => "GLBY",
            "firstPinYin" => "G",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "GY",
            "chineseName" => "圭亚那",
            "englishName" => "Guyana",
            "nativeName" => "South America",
            "nationalityCode" => "GUY",
            "phoneCode" => "592",
            "fullPinYin" => "GuiYaNa",
            "simplePinYin" => "GYN",
            "firstPinYin" => "G",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "GL",
            "chineseName" => "格陵兰",
            "englishName" => "Greenland",
            "nativeName" => "South America",
            "nationalityCode" => "GRL",
            "phoneCode" => "299",
            "fullPinYin" => "GeLingLan",
            "simplePinYin" => "GLL",
            "firstPinYin" => "G",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "KZ",
            "chineseName" => "哈萨克斯坦",
            "englishName" => "Kazakhstan",
            "nativeName" => "Middle East",
            "nationalityCode" => "KAZ",
            "phoneCode" => "7",
            "fullPinYin" => "HaSaKeSiTan",
            "simplePinYin" => "HSKST",
            "firstPinYin" => "H",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "KP",
            "chineseName" => "韩国",
            "englishName" => "Korea (North)",
            "nativeName" => "North Asia",
            "nationalityCode" => "PRK",
            "phoneCode" => "850",
            "fullPinYin" => "HanGuo",
            "simplePinYin" => "HG",
            "firstPinYin" => "H",
            "isHot" => 1,
        ),
        array(
            "countryCode" => "NL",
            "chineseName" => "荷兰",
            "englishName" => "Netherlands",
            "nativeName" => "Europe",
            "nationalityCode" => "NLD",
            "phoneCode" => "31",
            "fullPinYin" => "HeLan",
            "simplePinYin" => "HL",
            "firstPinYin" => "H",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "ME",
            "chineseName" => "黑山共和国",
            "englishName" => "Montenegro",
            "nativeName" => "Europe",
            "nationalityCode" => "MNE",
            "phoneCode" => "382",
            "fullPinYin" => "HeiShanGongHeGuo",
            "simplePinYin" => "HSGHG",
            "firstPinYin" => "H",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "AN",
            "chineseName" => "荷属安第列斯",
            "englishName" => "Netherlands Antilles",
            "nativeName" => "Others",
            "nationalityCode" => "ANT",
            "phoneCode" => "599",
            "fullPinYin" => "HeShuAnDiLieSi",
            "simplePinYin" => "HSADLS",
            "firstPinYin" => "H",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "HT",
            "chineseName" => "海地",
            "englishName" => "Haiti",
            "nativeName" => "South America",
            "nationalityCode" => "HTI",
            "phoneCode" => "509",
            "fullPinYin" => "HaiDe",
            "simplePinYin" => "HD",
            "firstPinYin" => "H",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "HN",
            "chineseName" => "洪都拉斯",
            "englishName" => "Honduras",
            "nativeName" => "South America",
            "nationalityCode" => "HND",
            "phoneCode" => "504",
            "fullPinYin" => "HongDouLaSi",
            "simplePinYin" => "HDLS",
            "firstPinYin" => "H",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "ZW",
            "chineseName" => "津巴布韦",
            "englishName" => "Zimbabwe",
            "nativeName" => "Africa",
            "nationalityCode" => "ZWE",
            "phoneCode" => "263",
            "fullPinYin" => "JinBaBuWei",
            "simplePinYin" => "JBBW",
            "firstPinYin" => "J",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "GA",
            "chineseName" => "加蓬",
            "englishName" => "Gabon",
            "nativeName" => "Africa",
            "nationalityCode" => "GAB",
            "phoneCode" => "241",
            "fullPinYin" => "JiaPeng",
            "simplePinYin" => "JP",
            "firstPinYin" => "J",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "GH",
            "chineseName" => "加纳",
            "englishName" => "Ghana",
            "nativeName" => "Africa",
            "nationalityCode" => "GHA",
            "phoneCode" => "233",
            "fullPinYin" => "JiaNa",
            "simplePinYin" => "JN",
            "firstPinYin" => "J",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "GN",
            "chineseName" => "几内亚",
            "englishName" => "Guinea",
            "nativeName" => "Africa",
            "nationalityCode" => "GIN",
            "phoneCode" => "224",
            "fullPinYin" => "JiNeiYa",
            "simplePinYin" => "JNY",
            "firstPinYin" => "J",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "GW",
            "chineseName" => "几内亚比绍",
            "englishName" => "Guinea-Bissau",
            "nativeName" => "Africa",
            "nationalityCode" => "GNB",
            "phoneCode" => "245",
            "fullPinYin" => "JiNeiYaBiShao",
            "simplePinYin" => "JNYBS",
            "firstPinYin" => "J",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "DJ",
            "chineseName" => "吉布提",
            "englishName" => "Djibouti",
            "nativeName" => "Africa",
            "nationalityCode" => "DJI",
            "phoneCode" => "253",
            "fullPinYin" => "JiBuDi",
            "simplePinYin" => "JBD",
            "firstPinYin" => "J",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "KI",
            "chineseName" => "基里巴斯",
            "englishName" => "Kiribati",
            "nativeName" => "Australia / New Zealand/ S W Pacific",
            "nationalityCode" => "KIR",
            "phoneCode" => "686",
            "fullPinYin" => "JiLiBaSi",
            "simplePinYin" => "JLBS",
            "firstPinYin" => "J",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "KG",
            "chineseName" => "吉尔吉斯斯坦",
            "englishName" => "Kyrgyzstan",
            "nativeName" => "Middle East",
            "nationalityCode" => "KGZ",
            "phoneCode" => "996",
            "fullPinYin" => "JiErJiSiSiTan",
            "simplePinYin" => "JEJSST",
            "firstPinYin" => "J",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "KH",
            "chineseName" => "柬埔寨",
            "englishName" => "Cambodia",
            "nativeName" => "S.E. Asia",
            "nationalityCode" => "KHM",
            "phoneCode" => "855",
            "fullPinYin" => "JianBuZhai",
            "simplePinYin" => "JBZ",
            "firstPinYin" => "J",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "CZ",
            "chineseName" => "捷克共和国",
            "englishName" => "Czech Republic",
            "nativeName" => "Europe",
            "nationalityCode" => "CZE",
            "phoneCode" => "420",
            "fullPinYin" => "JieKeGongHeGuo",
            "simplePinYin" => "JKGHG",
            "firstPinYin" => "J",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "CA",
            "chineseName" => "加拿大",
            "englishName" => "Canada",
            "nativeName" => "Noth America",
            "nationalityCode" => "CAN",
            "phoneCode" => "1",
            "fullPinYin" => "JiaNaDa",
            "simplePinYin" => "JND",
            "firstPinYin" => "J",
            "isHot" => 1,
        ),
        array(
            "countryCode" => "CI",
            "chineseName" => "科特迪瓦",
            "englishName" => "Cote D'Ivoire",
            "nativeName" => "Africa",
            "nationalityCode" => "CIV",
            "phoneCode" => "225",
            "fullPinYin" => "KeTeDiWa",
            "simplePinYin" => "KTDW",
            "firstPinYin" => "K",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "CM",
            "chineseName" => "喀麦隆",
            "englishName" => "Cameroon",
            "nativeName" => "Africa",
            "nationalityCode" => "CMR",
            "phoneCode" => "237",
            "fullPinYin" => "KaMaiLong",
            "simplePinYin" => "KML",
            "firstPinYin" => "K",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "KE",
            "chineseName" => "肯尼亚",
            "englishName" => "Kenya",
            "nativeName" => "Africa",
            "nationalityCode" => "KEN",
            "phoneCode" => "254",
            "fullPinYin" => "KenNiYa",
            "simplePinYin" => "KNY",
            "firstPinYin" => "K",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "KM",
            "chineseName" => "科摩罗",
            "englishName" => "Comoros",
            "nativeName" => "Africa",
            "nationalityCode" => "COM",
            "phoneCode" => "269",
            "fullPinYin" => "KeMaLuo",
            "simplePinYin" => "KML",
            "firstPinYin" => "K",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "CK",
            "chineseName" => "库克群岛",
            "englishName" => "Cook Islands",
            "nativeName" => "Australia / New Zealand/ S W Pacific",
            "nationalityCode" => "COK",
            "phoneCode" => "682",
            "fullPinYin" => "KuKeQunDao",
            "simplePinYin" => "KKQD",
            "firstPinYin" => "K",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "CC",
            "chineseName" => "科科斯(基林)群岛",
            "englishName" => "Cocos (keeling) Islands",
            "nativeName" => "South America",
            "nationalityCode" => "CCK",
            "phoneCode" => "61",
            "fullPinYin" => "KeKeSi(JiLin)QunDao",
            "simplePinYin" => "KKS(JL)QD",
            "firstPinYin" => "K",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "HR",
            "chineseName" => "克罗地亚",
            "englishName" => "Croatia",
            "nativeName" => "Europe",
            "nationalityCode" => "HRV",
            "phoneCode" => "385",
            "fullPinYin" => "KeLuoDeYa",
            "simplePinYin" => "KLDY",
            "firstPinYin" => "K",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "KY",
            "chineseName" => "开曼群岛",
            "englishName" => "Cayman Islands",
            "nativeName" => "South America",
            "nationalityCode" => "CYM",
            "phoneCode" => "1345",
            "fullPinYin" => "KaiManQunDao",
            "simplePinYin" => "KMQD",
            "firstPinYin" => "K",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "KW",
            "chineseName" => "科威特",
            "englishName" => "Kuwait",
            "nativeName" => "Middle East",
            "nationalityCode" => "KWT",
            "phoneCode" => "965",
            "fullPinYin" => "KeWeiTe",
            "simplePinYin" => "KWT",
            "firstPinYin" => "K",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "QA",
            "chineseName" => "卡塔尔",
            "englishName" => "Qatar",
            "nativeName" => "Middle East",
            "nationalityCode" => "QAT",
            "phoneCode" => "974",
            "fullPinYin" => "KaDaEr",
            "simplePinYin" => "KDE",
            "firstPinYin" => "K",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "LS",
            "chineseName" => "莱索托",
            "englishName" => "Lesotho",
            "nativeName" => "Africa",
            "nationalityCode" => "LSO",
            "phoneCode" => "266",
            "fullPinYin" => "LaiSuoTuo",
            "simplePinYin" => "LST",
            "firstPinYin" => "L",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "LR",
            "chineseName" => "利比里亚",
            "englishName" => "Liberia",
            "nativeName" => "Africa",
            "nationalityCode" => "LBR",
            "phoneCode" => "231",
            "fullPinYin" => "LiBiLiYa",
            "simplePinYin" => "LBLY",
            "firstPinYin" => "L",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "RE",
            "chineseName" => "留尼旺岛",
            "englishName" => "Reunion",
            "nativeName" => "Others",
            "nationalityCode" => "REU",
            "phoneCode" => "262",
            "fullPinYin" => "LiuNiWangDao",
            "simplePinYin" => "LNWD",
            "firstPinYin" => "L",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "RW",
            "chineseName" => "卢旺达",
            "englishName" => "Rwanda",
            "nativeName" => "Africa",
            "nationalityCode" => "RWA",
            "phoneCode" => "250",
            "fullPinYin" => "LuWangDa",
            "simplePinYin" => "LWD",
            "firstPinYin" => "L",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "LA",
            "chineseName" => "老挝人民民主共和国",
            "englishName" => "Lao People's Democratic Republic",
            "nativeName" => "S.E. Asia",
            "nationalityCode" => "LAO",
            "phoneCode" => "856",
            "fullPinYin" => "LaoWoRenMinMinZhuGongHeGuo",
            "simplePinYin" => "LWRMMZGHG",
            "firstPinYin" => "L",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "LU",
            "chineseName" => "卢森堡",
            "englishName" => "Luxembourg",
            "nativeName" => "Europe",
            "nationalityCode" => "LUX",
            "phoneCode" => "352",
            "fullPinYin" => "LuSenBao",
            "simplePinYin" => "LSB",
            "firstPinYin" => "L",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "LT",
            "chineseName" => "立陶宛",
            "englishName" => "Lithuania",
            "nativeName" => "Europe",
            "nationalityCode" => "LTU",
            "phoneCode" => "370",
            "fullPinYin" => "LiTaoWan",
            "simplePinYin" => "LTW",
            "firstPinYin" => "L",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "LV",
            "chineseName" => "拉脱维亚",
            "englishName" => "Latvia",
            "nativeName" => "Europe",
            "nationalityCode" => "LVA",
            "phoneCode" => "371",
            "fullPinYin" => "LaTuoWeiYa",
            "simplePinYin" => "LTWY",
            "firstPinYin" => "L",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "RO",
            "chineseName" => "罗马尼亚",
            "englishName" => "Romania",
            "nativeName" => "Europe",
            "nationalityCode" => "ROU",
            "phoneCode" => "40",
            "fullPinYin" => "LuoMaNiYa",
            "simplePinYin" => "LMNY",
            "firstPinYin" => "L",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "LB",
            "chineseName" => "黎巴嫩",
            "englishName" => "Lebanon",
            "nativeName" => "Middle East",
            "nationalityCode" => "LBN",
            "phoneCode" => "961",
            "fullPinYin" => "LiBaNen",
            "simplePinYin" => "LBN",
            "firstPinYin" => "L",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "MA",
            "chineseName" => "摩洛哥",
            "englishName" => "Morocco",
            "nativeName" => "Middle East",
            "nationalityCode" => "MAR",
            "phoneCode" => "212",
            "fullPinYin" => "MaLuoGe",
            "simplePinYin" => "MLG",
            "firstPinYin" => "M",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "MW",
            "chineseName" => "马拉维",
            "englishName" => "Malawi",
            "nativeName" => "Africa",
            "nationalityCode" => "MWI",
            "phoneCode" => "265",
            "fullPinYin" => "MaLaWei",
            "simplePinYin" => "MLW",
            "firstPinYin" => "M",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "MZ",
            "chineseName" => "莫桑比克",
            "englishName" => "Mozambique",
            "nativeName" => "Africa",
            "nationalityCode" => "MOZ",
            "phoneCode" => "258",
            "fullPinYin" => "MoSangBiKe",
            "simplePinYin" => "MSBK",
            "firstPinYin" => "M",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "ML",
            "chineseName" => "马里",
            "englishName" => "Mali",
            "nativeName" => "Africa",
            "nationalityCode" => "MLI",
            "phoneCode" => "223",
            "fullPinYin" => "MaLi",
            "simplePinYin" => "ML",
            "firstPinYin" => "M",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "MR",
            "chineseName" => "毛里塔尼亚",
            "englishName" => "Mauritania",
            "nativeName" => "Africa",
            "nationalityCode" => "MRT",
            "phoneCode" => "222",
            "fullPinYin" => "MaoLiDaNiYa",
            "simplePinYin" => "MLDNY",
            "firstPinYin" => "M",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "YT",
            "chineseName" => "马约特岛",
            "englishName" => "Mayotte",
            "nativeName" => "Others",
            "nationalityCode" => "MYT",
            "phoneCode" => "262",
            "fullPinYin" => "MaYaoTeDao",
            "simplePinYin" => "MYTD",
            "firstPinYin" => "M",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "MG",
            "chineseName" => "马达加斯加",
            "englishName" => "Madagascar",
            "nativeName" => "Africa",
            "nationalityCode" => "MDG",
            "phoneCode" => "261",
            "fullPinYin" => "MaDaJiaSiJia",
            "simplePinYin" => "MDJSJ",
            "firstPinYin" => "M",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "MU",
            "chineseName" => "毛里求斯",
            "englishName" => "Mauritius",
            "nativeName" => "Africa",
            "nationalityCode" => "MUS",
            "phoneCode" => "230",
            "fullPinYin" => "MaoLiQiuSi",
            "simplePinYin" => "MLQS",
            "firstPinYin" => "M",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "BD",
            "chineseName" => "孟加拉国",
            "englishName" => "Bangladesh",
            "nativeName" => "India & Sub. Continents",
            "nationalityCode" => "BGD",
            "phoneCode" => "880",
            "fullPinYin" => "MengJiaLaGuo",
            "simplePinYin" => "MJLG",
            "firstPinYin" => "M",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "MV",
            "chineseName" => "马尔代夫",
            "englishName" => "Maldives",
            "nativeName" => "India & Sub. Continents",
            "nationalityCode" => "MDV",
            "phoneCode" => "960",
            "fullPinYin" => "MaErDaiFu",
            "simplePinYin" => "MEDF",
            "firstPinYin" => "M",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "US",
            "chineseName" => "美国",
            "englishName" => "United States",
            "nativeName" => "Noth America",
            "nationalityCode" => "USA",
            "phoneCode" => "1",
            "fullPinYin" => "MeiGuo",
            "simplePinYin" => "MG",
            "firstPinYin" => "M",
            "isHot" => 1,
        ),
        array(
            "countryCode" => "AS",
            "chineseName" => "美属萨摩亚",
            "englishName" => "American Samoa",
            "nativeName" => "Others",
            "nationalityCode" => "ASM",
            "phoneCode" => "684",
            "fullPinYin" => "MeiShuSaMaYa",
            "simplePinYin" => "MSSMY",
            "firstPinYin" => "M",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "FM",
            "chineseName" => "密克罗尼西亚联邦",
            "englishName" => "Micronesia Federated States of",
            "nativeName" => "Australia / New Zealand/ S W Pacific",
            "nationalityCode" => "FSM",
            "phoneCode" => "691",
            "fullPinYin" => "MiKeLuoNiXiYaLianBang",
            "simplePinYin" => "MKLNXYLB",
            "firstPinYin" => "M",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "MH",
            "chineseName" => "马绍尔群岛",
            "englishName" => "Marshall Islands",
            "nativeName" => "Australia / New Zealand/ S W Pacific",
            "nationalityCode" => "MHL",
            "phoneCode" => "692",
            "fullPinYin" => "MaShaoErQunDao",
            "simplePinYin" => "MSEQD",
            "firstPinYin" => "M",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "MM",
            "chineseName" => "缅甸",
            "englishName" => "Myanmar",
            "nativeName" => "S.E. Asia",
            "nationalityCode" => "MMR",
            "phoneCode" => "95",
            "fullPinYin" => "MianDian",
            "simplePinYin" => "MD",
            "firstPinYin" => "M",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "MY",
            "chineseName" => "马来西亚",
            "englishName" => "Malaysia",
            "nativeName" => "S.E. Asia",
            "nationalityCode" => "MYS",
            "phoneCode" => "60",
            "fullPinYin" => "MaLaiXiYa",
            "simplePinYin" => "MLXY",
            "firstPinYin" => "M",
            "isHot" => 1,
        ),
        array(
            "countryCode" => "MN",
            "chineseName" => "蒙古",
            "englishName" => "Mongolia",
            "nativeName" => "North Asia",
            "nationalityCode" => "MNG",
            "phoneCode" => "976",
            "fullPinYin" => "MengGu",
            "simplePinYin" => "MG",
            "firstPinYin" => "M",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "MC",
            "chineseName" => "摩纳哥",
            "englishName" => "Monaco",
            "nativeName" => "Europe",
            "nationalityCode" => "MCO",
            "phoneCode" => "377",
            "fullPinYin" => "MaNaGe",
            "simplePinYin" => "MNG",
            "firstPinYin" => "M",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "MT",
            "chineseName" => "马耳他",
            "englishName" => "Malta",
            "nativeName" => "Europe",
            "nationalityCode" => "MLT",
            "phoneCode" => "356",
            "fullPinYin" => "MaErTa",
            "simplePinYin" => "MET",
            "firstPinYin" => "M",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "MD",
            "chineseName" => "摩尔多瓦共和国",
            "englishName" => "Moldova Republic of",
            "nativeName" => "Europe",
            "nationalityCode" => "MDA",
            "phoneCode" => "373",
            "fullPinYin" => "MaErDuoWaGongHeGuo",
            "simplePinYin" => "MEDWGHG",
            "firstPinYin" => "M",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "MQ",
            "chineseName" => "马提尼克",
            "englishName" => "Martinique",
            "nativeName" => "Others",
            "nationalityCode" => "MTQ",
            "phoneCode" => "596",
            "fullPinYin" => "MaDiNiKe",
            "simplePinYin" => "MDNK",
            "firstPinYin" => "M",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "MS",
            "chineseName" => "蒙特塞拉特，背风群岛",
            "englishName" => "Montserrat, Leeward Islands",
            "nativeName" => "Others",
            "nationalityCode" => "MSR",
            "phoneCode" => "1",
            "fullPinYin" => "MengTeSaiLaTe，BeiFengQunDao",
            "simplePinYin" => "MTSLT，BFQD",
            "firstPinYin" => "M",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "VI",
            "chineseName" => "美属维京群岛",
            "englishName" => "Virgin Islands, Us",
            "nativeName" => "South America",
            "nationalityCode" => "VIR",
            "phoneCode" => "1340",
            "fullPinYin" => "MeiShuWeiJingQunDao",
            "simplePinYin" => "MSWJQD",
            "firstPinYin" => "M",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "MX",
            "chineseName" => "墨西哥",
            "englishName" => "Mexico",
            "nativeName" => "South America",
            "nationalityCode" => "MEX",
            "phoneCode" => "52",
            "fullPinYin" => "MoXiGe",
            "simplePinYin" => "MXG",
            "firstPinYin" => "M",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "NA",
            "chineseName" => "纳米比亚",
            "englishName" => "Namibia",
            "nativeName" => "Africa",
            "nationalityCode" => "NAM",
            "phoneCode" => "264",
            "fullPinYin" => "NaMiBiYa",
            "simplePinYin" => "NMBY",
            "firstPinYin" => "N",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "ZA",
            "chineseName" => "南非",
            "englishName" => "South Africa",
            "nativeName" => "Africa",
            "nationalityCode" => "ZAF",
            "phoneCode" => "27",
            "fullPinYin" => "NaFei",
            "simplePinYin" => "NF",
            "firstPinYin" => "N",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "NE",
            "chineseName" => "尼日尔",
            "englishName" => "Niger",
            "nativeName" => "Africa",
            "nationalityCode" => "NER",
            "phoneCode" => "227",
            "fullPinYin" => "NiRiEr",
            "simplePinYin" => "NRE",
            "firstPinYin" => "N",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "NG",
            "chineseName" => "尼日利亚",
            "englishName" => "Nigeria",
            "nativeName" => "Africa",
            "nationalityCode" => "NGA",
            "phoneCode" => "234",
            "fullPinYin" => "NiRiLiYa",
            "simplePinYin" => "NRLY",
            "firstPinYin" => "N",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "NF",
            "chineseName" => "诺福克岛",
            "englishName" => "Norfolk Island",
            "nativeName" => "Australia / New Zealand/ S W Pacific",
            "nationalityCode" => "NFK",
            "phoneCode" => "6723",
            "fullPinYin" => "NuoFuKeDao",
            "simplePinYin" => "NFKD",
            "firstPinYin" => "N",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "NR",
            "chineseName" => "瑙鲁",
            "englishName" => "Nauru",
            "nativeName" => "Australia / New Zealand/ S W Pacific",
            "nationalityCode" => "NRU",
            "phoneCode" => "674",
            "fullPinYin" => "NaoLu",
            "simplePinYin" => "NL",
            "firstPinYin" => "N",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "NU",
            "chineseName" => "纽埃",
            "englishName" => "Niue",
            "nativeName" => "Australia / New Zealand/ S W Pacific",
            "nationalityCode" => "NIU",
            "phoneCode" => "683",
            "fullPinYin" => "NiuAi",
            "simplePinYin" => "NA",
            "firstPinYin" => "N",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "NP",
            "chineseName" => "尼泊尔",
            "englishName" => "Nepal",
            "nativeName" => "India & Sub. Continents",
            "nationalityCode" => "NPL",
            "phoneCode" => "977",
            "fullPinYin" => "NiBoEr",
            "simplePinYin" => "NBE",
            "firstPinYin" => "N",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "NO",
            "chineseName" => "挪威",
            "englishName" => "Norway",
            "nativeName" => "Europe",
            "nationalityCode" => "NOR",
            "phoneCode" => "47",
            "fullPinYin" => "NuoWei",
            "simplePinYin" => "NW",
            "firstPinYin" => "N",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "NI",
            "chineseName" => "尼加拉瓜",
            "englishName" => "Nicaragua",
            "nativeName" => "South America",
            "nationalityCode" => "NIC",
            "phoneCode" => "505",
            "fullPinYin" => "NiJiaLaGua",
            "simplePinYin" => "NJLG",
            "firstPinYin" => "N",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "PT",
            "chineseName" => "葡萄牙",
            "englishName" => "Portugal",
            "nativeName" => "Europe",
            "nationalityCode" => "PRT",
            "phoneCode" => "351",
            "fullPinYin" => "PuTaoYa",
            "simplePinYin" => "PTY",
            "firstPinYin" => "P",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "MK",
            "chineseName" => "前南斯拉夫的马其顿共和国",
            "englishName" => "Macedonia Former Yugoslav Republic of",
            "nativeName" => "Europe",
            "nationalityCode" => "MKD",
            "phoneCode" => "389",
            "fullPinYin" => "QianNaSiLaFuDeMaJiDuGongHeGuo",
            "simplePinYin" => "QNSLFDMJDGHG",
            "firstPinYin" => "Q",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "JP",
            "chineseName" => "日本",
            "englishName" => "Japan",
            "nativeName" => "North Asia",
            "nationalityCode" => "JPN",
            "phoneCode" => "81",
            "fullPinYin" => "RiBen",
            "simplePinYin" => "RB",
            "firstPinYin" => "R",
            "isHot" => 1,
        ),
        array(
            "countryCode" => "CH",
            "chineseName" => "瑞士",
            "englishName" => "Switzerland",
            "nativeName" => "Europe",
            "nationalityCode" => "CHE",
            "phoneCode" => "41",
            "fullPinYin" => "RuiShi",
            "simplePinYin" => "RS",
            "firstPinYin" => "R",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "SE",
            "chineseName" => "瑞典",
            "englishName" => "Sweden",
            "nativeName" => "Europe",
            "nationalityCode" => "SWE",
            "phoneCode" => "46",
            "fullPinYin" => "RuiDian",
            "simplePinYin" => "RD",
            "firstPinYin" => "R",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "SD",
            "chineseName" => "苏丹",
            "englishName" => "Sudan",
            "nativeName" => "Africa",
            "nationalityCode" => "SDN",
            "phoneCode" => "249",
            "fullPinYin" => "SuDan",
            "simplePinYin" => "SD",
            "firstPinYin" => "S",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "SZ",
            "chineseName" => "斯威士兰",
            "englishName" => "Swaziland",
            "nativeName" => "Africa",
            "nationalityCode" => "SWZ",
            "phoneCode" => "268",
            "fullPinYin" => "SiWeiShiLan",
            "simplePinYin" => "SWSL",
            "firstPinYin" => "S",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "SH",
            "chineseName" => "圣赫勒拿",
            "englishName" => "Saint Helena",
            "nativeName" => "Others",
            "nationalityCode" => "SHN",
            "phoneCode" => "290",
            "fullPinYin" => "ShengHeLeNa",
            "simplePinYin" => "SHLN",
            "firstPinYin" => "S",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "SL",
            "chineseName" => "塞拉利昂",
            "englishName" => "Sierra Leone",
            "nativeName" => "Africa",
            "nationalityCode" => "SLE",
            "phoneCode" => "232",
            "fullPinYin" => "SaiLaLiAng",
            "simplePinYin" => "SLLA",
            "firstPinYin" => "S",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "SN",
            "chineseName" => "塞内加尔",
            "englishName" => "Senegal",
            "nativeName" => "Africa",
            "nationalityCode" => "SEN",
            "phoneCode" => "221",
            "fullPinYin" => "SaiNeiJiaEr",
            "simplePinYin" => "SNJE",
            "firstPinYin" => "S",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "ST",
            "chineseName" => "圣多美和普林西比",
            "englishName" => "Sao Tome and Principe",
            "nativeName" => "Africa",
            "nationalityCode" => "STP",
            "phoneCode" => "239",
            "fullPinYin" => "ShengDuoMeiHePuLinXiBi",
            "simplePinYin" => "SDMHPLXB",
            "firstPinYin" => "S",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "SC",
            "chineseName" => "塞舌尔共和国",
            "englishName" => "Seychelles",
            "nativeName" => "Africa",
            "nationalityCode" => "SYC",
            "phoneCode" => "248",
            "fullPinYin" => "SaiSheErGongHeGuo",
            "simplePinYin" => "SSEGHG",
            "firstPinYin" => "S",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "SO",
            "chineseName" => "索马里",
            "englishName" => "Somalia",
            "nativeName" => "Africa",
            "nationalityCode" => "SOM",
            "phoneCode" => "252",
            "fullPinYin" => "SuoMaLi",
            "simplePinYin" => "SML",
            "firstPinYin" => "S",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "LK",
            "chineseName" => "斯里兰卡",
            "englishName" => "Sri Lanka",
            "nativeName" => "India & Sub. Continents",
            "nationalityCode" => "LKA",
            "phoneCode" => "94",
            "fullPinYin" => "SiLiLanKa",
            "simplePinYin" => "SLLK",
            "firstPinYin" => "S",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "CX",
            "chineseName" => "圣诞岛，印度洋",
            "englishName" => "Christmas Island, Indian Ocean",
            "nativeName" => "Australia / New Zealand/ S W Pacific",
            "nationalityCode" => "CXR",
            "phoneCode" => "61",
            "fullPinYin" => "ShengDanDao，YinDuXiang",
            "simplePinYin" => "SDD，YDX",
            "firstPinYin" => "S",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "SB",
            "chineseName" => "所罗门群岛",
            "englishName" => "Solomon Islands",
            "nativeName" => "Australia / New Zealand/ S W Pacific",
            "nationalityCode" => "SLB",
            "phoneCode" => "677",
            "fullPinYin" => "SuoLuoMenQunDao",
            "simplePinYin" => "SLMQD",
            "firstPinYin" => "S",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "TO",
            "chineseName" => "汤加",
            "englishName" => "Tonga",
            "nativeName" => "Australia / New Zealand/ S W Pacific",
            "nationalityCode" => "TON",
            "phoneCode" => "676",
            "fullPinYin" => "ShangJia",
            "simplePinYin" => "SJ",
            "firstPinYin" => "S",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "WS",
            "chineseName" => "萨摩亚群岛",
            "englishName" => "Samoa",
            "nativeName" => "Australia / New Zealand/ S W Pacific",
            "nationalityCode" => "WSM",
            "phoneCode" => "685",
            "fullPinYin" => "SaMaYaQunDao",
            "simplePinYin" => "SMYQD",
            "firstPinYin" => "S",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "CY",
            "chineseName" => "塞浦路斯",
            "englishName" => "Cyprus",
            "nativeName" => "Europe",
            "nationalityCode" => "CYP",
            "phoneCode" => "357",
            "fullPinYin" => "SaiPuLuSi",
            "simplePinYin" => "SPLS",
            "firstPinYin" => "S",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "RS",
            "chineseName" => "塞尔维亚",
            "englishName" => "Serbia",
            "nativeName" => "Europe",
            "nationalityCode" => "SRB",
            "phoneCode" => "381",
            "fullPinYin" => "SaiErWeiYa",
            "simplePinYin" => "SEWY",
            "firstPinYin" => "S",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "SI",
            "chineseName" => "斯洛文尼亚",
            "englishName" => "Slovenia",
            "nativeName" => "Europe",
            "nationalityCode" => "SVN",
            "phoneCode" => "386",
            "fullPinYin" => "SiLuoWenNiYa",
            "simplePinYin" => "SLWNY",
            "firstPinYin" => "S",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "SK",
            "chineseName" => "斯洛伐克",
            "englishName" => "Slovakia",
            "nativeName" => "Europe",
            "nationalityCode" => "SVK",
            "phoneCode" => "421",
            "fullPinYin" => "SiLuoFaKe",
            "simplePinYin" => "SLFK",
            "firstPinYin" => "S",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "KN",
            "chineseName" => "圣基思和尼维斯，背风群岛",
            "englishName" => "Saint Kitts and Nevis, Leeward Islands",
            "nativeName" => "South America",
            "nationalityCode" => "KNA",
            "phoneCode" => "869",
            "fullPinYin" => "ShengJiSaiHeNiWeiSi，BeiFengQunDao",
            "simplePinYin" => "SJSHNWS，BFQD",
            "firstPinYin" => "S",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "LC",
            "chineseName" => "圣卢西亚",
            "englishName" => "Saint Lucia",
            "nativeName" => "South America",
            "nationalityCode" => "LCA",
            "phoneCode" => "1",
            "fullPinYin" => "ShengLuXiYa",
            "simplePinYin" => "SLXY",
            "firstPinYin" => "S",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "VC",
            "chineseName" => "圣文森特及格林纳丁斯",
            "englishName" => "St Vincent and the Grenadines",
            "nativeName" => "South America",
            "nationalityCode" => "VCT",
            "phoneCode" => "223",
            "fullPinYin" => "ShengWenSenTeJiGeLinNaDingSi",
            "simplePinYin" => "SWSTJGLNDS",
            "firstPinYin" => "S",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "SV",
            "chineseName" => "萨尔瓦多",
            "englishName" => "El Salvador",
            "nativeName" => "South America",
            "nationalityCode" => "SLV",
            "phoneCode" => "503",
            "fullPinYin" => "SaErWaDuo",
            "simplePinYin" => "SEWD",
            "firstPinYin" => "S",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "SR",
            "chineseName" => "苏里南",
            "englishName" => "Suriname",
            "nativeName" => "South America",
            "nationalityCode" => "SUR",
            "phoneCode" => "597",
            "fullPinYin" => "SuLiNa",
            "simplePinYin" => "SLN",
            "firstPinYin" => "S",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "SA",
            "chineseName" => "沙竺阿拉伯",
            "englishName" => "Saudi Arabia",
            "nativeName" => "Middle East",
            "nationalityCode" => "SAU",
            "phoneCode" => "966",
            "fullPinYin" => "ShaZhuALaBai",
            "simplePinYin" => "SZALB",
            "firstPinYin" => "S",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "PM",
            "chineseName" => "圣皮埃尔和密克隆",
            "englishName" => "Saint Pierre and Miquelon",
            "nativeName" => "Others",
            "nationalityCode" => "SPM",
            "phoneCode" => "508",
            "fullPinYin" => "ShengPiAiErHeMiKeLong",
            "simplePinYin" => "SPAEHMKL",
            "firstPinYin" => "S",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "TN",
            "chineseName" => "突尼斯",
            "englishName" => "Tunisia",
            "nativeName" => "Middle East",
            "nationalityCode" => "TUN",
            "phoneCode" => "216",
            "fullPinYin" => "TuNiSi",
            "simplePinYin" => "TNS",
            "firstPinYin" => "T",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "TZ",
            "chineseName" => "坦桑尼亚联合共和国",
            "englishName" => "Tanzania United Republic of",
            "nativeName" => "Africa",
            "nationalityCode" => "TZA",
            "phoneCode" => "255",
            "fullPinYin" => "TanSangNiYaLianGeGongHeGuo",
            "simplePinYin" => "TSNYLGGHG",
            "firstPinYin" => "T",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "TV",
            "chineseName" => "图瓦卢",
            "englishName" => "Tuvalu",
            "nativeName" => "Australia / New Zealand/ S W Pacific",
            "nationalityCode" => "TUV",
            "phoneCode" => "688",
            "fullPinYin" => "TuWaLu",
            "simplePinYin" => "TWL",
            "firstPinYin" => "T",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "TM",
            "chineseName" => "土库曼斯坦",
            "englishName" => "Turkmenistan",
            "nativeName" => "Others",
            "nationalityCode" => "TKM",
            "phoneCode" => "993",
            "fullPinYin" => "TuKuManSiTan",
            "simplePinYin" => "TKMST",
            "firstPinYin" => "T",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "TH",
            "chineseName" => "泰国",
            "englishName" => "Thailand",
            "nativeName" => "S.E. Asia",
            "nationalityCode" => "THA",
            "phoneCode" => "66",
            "fullPinYin" => "TaiGuo",
            "simplePinYin" => "TG",
            "firstPinYin" => "T",
            "isHot" => 1,
        ),
        array(
            "countryCode" => "TW",
            "chineseName" => "台湾",
            "englishName" => "Taiwan",
            "nativeName" => "North Asia",
            "nationalityCode" => "TWN",
            "phoneCode" => "886",
            "fullPinYin" => "TaiWan",
            "simplePinYin" => "TW",
            "firstPinYin" => "T",
            "isHot" => 1,
        ),
        array(
            "countryCode" => "TR",
            "chineseName" => "土耳其",
            "englishName" => "Turkey",
            "nativeName" => "Middle East",
            "nationalityCode" => "TUR",
            "phoneCode" => "90",
            "fullPinYin" => "TuErJi",
            "simplePinYin" => "TEJ",
            "firstPinYin" => "T",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "TC",
            "chineseName" => "特克斯科斯群岛",
            "englishName" => "Turks and Caicos Islands",
            "nativeName" => "Others",
            "nationalityCode" => "TCA",
            "phoneCode" => "1649",
            "fullPinYin" => "TeKeSiKeSiQunDao",
            "simplePinYin" => "TKSKSQD",
            "firstPinYin" => "T",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "TT",
            "chineseName" => "特立尼达和多巴哥",
            "englishName" => "Trinidad and Tobago",
            "nativeName" => "South America",
            "nationalityCode" => "TTO",
            "phoneCode" => "1868",
            "fullPinYin" => "TeLiNiDaHeDuoBaGe",
            "simplePinYin" => "TLNDHDBG",
            "firstPinYin" => "T",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "UG",
            "chineseName" => "乌干达",
            "englishName" => "Uganda",
            "nativeName" => "Africa",
            "nationalityCode" => "UGA",
            "phoneCode" => "256",
            "fullPinYin" => "WuGanDa",
            "simplePinYin" => "WGD",
            "firstPinYin" => "W",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "VU",
            "chineseName" => "瓦努阿图",
            "englishName" => "Vanuatu",
            "nativeName" => "Australia / New Zealand/ S W Pacific",
            "nationalityCode" => "VUT",
            "phoneCode" => "678",
            "fullPinYin" => "WaNuATu",
            "simplePinYin" => "WNAT",
            "firstPinYin" => "W",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "WF",
            "chineseName" => "瓦利斯和富图纳群岛",
            "englishName" => "Wallis and Futuna Islands",
            "nativeName" => "South America",
            "nationalityCode" => "WLF",
            "phoneCode" => "681",
            "fullPinYin" => "WaLiSiHeFuTuNaQunDao",
            "simplePinYin" => "WLSHFTNQD",
            "firstPinYin" => "W",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "UZ",
            "chineseName" => "乌兹别克斯坦",
            "englishName" => "Uzbekistan",
            "nativeName" => "Middle East",
            "nationalityCode" => "UZB",
            "phoneCode" => "998",
            "fullPinYin" => "WuCiBieKeSiTan",
            "simplePinYin" => "WCBKST",
            "firstPinYin" => "W",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "BN",
            "chineseName" => "文莱达鲁萨兰国",
            "englishName" => "Brunei Darussalam",
            "nativeName" => "S.E. Asia",
            "nationalityCode" => "BRN",
            "phoneCode" => "673",
            "fullPinYin" => "WenLaiDaLuSaLanGuo",
            "simplePinYin" => "WLDLSLG",
            "firstPinYin" => "W",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "UA",
            "chineseName" => "乌克兰",
            "englishName" => "Ukraine",
            "nativeName" => "Europe",
            "nationalityCode" => "UKR",
            "phoneCode" => "380",
            "fullPinYin" => "WuKeLan",
            "simplePinYin" => "WKL",
            "firstPinYin" => "W",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "GT",
            "chineseName" => "危地马拉",
            "englishName" => "Guatemala",
            "nativeName" => "South America",
            "nationalityCode" => "GTM",
            "phoneCode" => "502",
            "fullPinYin" => "WeiDeMaLa",
            "simplePinYin" => "WDML",
            "firstPinYin" => "W",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "VE",
            "chineseName" => "委内瑞拉",
            "englishName" => "Venezuela",
            "nativeName" => "South America",
            "nationalityCode" => "VEN",
            "phoneCode" => "58",
            "fullPinYin" => "WeiNeiRuiLa",
            "simplePinYin" => "WNRL",
            "firstPinYin" => "W",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "UY",
            "chineseName" => "乌拉圭",
            "englishName" => "Uruguay",
            "nativeName" => "South America",
            "nationalityCode" => "URY",
            "phoneCode" => "598",
            "fullPinYin" => "WuLaGui",
            "simplePinYin" => "WLG",
            "firstPinYin" => "W",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "NC",
            "chineseName" => "新赫里多尼亚",
            "englishName" => "New Caledonia",
            "nativeName" => "South America",
            "nationalityCode" => "NCL",
            "phoneCode" => "687",
            "fullPinYin" => "XinHeLiDuoNiYa",
            "simplePinYin" => "XHLDNY",
            "firstPinYin" => "X",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "NZ",
            "chineseName" => "新西兰",
            "englishName" => "New Zealand",
            "nativeName" => "Australia / New Zealand/ S W Pacific",
            "nationalityCode" => "NZL",
            "phoneCode" => "64",
            "fullPinYin" => "XinXiLan",
            "simplePinYin" => "XXL",
            "firstPinYin" => "X",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "SG",
            "chineseName" => "新加坡",
            "englishName" => "Singapore",
            "nativeName" => "S.E. Asia",
            "nationalityCode" => "SGP",
            "phoneCode" => "65",
            "fullPinYin" => "XinJiaPo",
            "simplePinYin" => "XJP",
            "firstPinYin" => "X",
            "isHot" => 1,
        ),
        array(
            "countryCode" => "ES",
            "chineseName" => "西班牙",
            "englishName" => "Spain",
            "nativeName" => "Europe",
            "nationalityCode" => "ESP",
            "phoneCode" => "34",
            "fullPinYin" => "XiBanYa",
            "simplePinYin" => "XBY",
            "firstPinYin" => "X",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "GR",
            "chineseName" => "希腊",
            "englishName" => "Greece",
            "nativeName" => "Europe",
            "nationalityCode" => "GRC",
            "phoneCode" => "30",
            "fullPinYin" => "XiLa",
            "simplePinYin" => "XL",
            "firstPinYin" => "X",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "HU",
            "chineseName" => "匈牙利",
            "englishName" => "Hungary",
            "nativeName" => "Europe",
            "nationalityCode" => "HUN",
            "phoneCode" => "36",
            "fullPinYin" => "XiongYaLi",
            "simplePinYin" => "XYL",
            "firstPinYin" => "X",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "IN",
            "chineseName" => "印度",
            "englishName" => "India",
            "nativeName" => "India & Sub. Continents",
            "nationalityCode" => "IND",
            "phoneCode" => "91",
            "fullPinYin" => "YinDu",
            "simplePinYin" => "YD",
            "firstPinYin" => "Y",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "ID",
            "chineseName" => "印度尼西亚",
            "englishName" => "Indonesia",
            "nativeName" => "S.E. Asia",
            "nationalityCode" => "IDN",
            "phoneCode" => "62",
            "fullPinYin" => "YinDuNiXiYa",
            "simplePinYin" => "YDNXY",
            "firstPinYin" => "Y",
            "isHot" => 1,
        ),
        array(
            "countryCode" => "VN",
            "chineseName" => "越南",
            "englishName" => "Vietnam",
            "nativeName" => "S.E. Asia",
            "nationalityCode" => "VMN",
            "phoneCode" => "84",
            "fullPinYin" => "YueNa",
            "simplePinYin" => "YN",
            "firstPinYin" => "Y",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "GB",
            "chineseName" => "英国",
            "englishName" => "United Kingdom",
            "nativeName" => "Europe",
            "nationalityCode" => "GBR",
            "phoneCode" => "44",
            "fullPinYin" => "YingGuo",
            "simplePinYin" => "YG",
            "firstPinYin" => "Y",
            "isHot" => 1,
        ),
        array(
            "countryCode" => "IT",
            "chineseName" => "意大利",
            "englishName" => "Italy",
            "nativeName" => "Europe",
            "nationalityCode" => "ITA",
            "phoneCode" => "39",
            "fullPinYin" => "YiDaLi",
            "simplePinYin" => "YDL",
            "firstPinYin" => "Y",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "AM",
            "chineseName" => "亚美尼亚",
            "englishName" => "Armenia",
            "nativeName" => "Europe",
            "nationalityCode" => "ARM",
            "phoneCode" => "374",
            "fullPinYin" => "YaMeiNiYa",
            "simplePinYin" => "YMNY",
            "firstPinYin" => "Y",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "JM",
            "chineseName" => "牙买加",
            "englishName" => "Jamaica",
            "nativeName" => "South America",
            "nationalityCode" => "JAM",
            "phoneCode" => "1876",
            "fullPinYin" => "YaMaiJia",
            "simplePinYin" => "YMJ",
            "firstPinYin" => "Y",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "VG",
            "chineseName" => "英属维京群岛",
            "englishName" => "Virgin Islands, British",
            "nativeName" => "South America",
            "nationalityCode" => "VGB",
            "phoneCode" => "1",
            "fullPinYin" => "YingShuWeiJingQunDao",
            "simplePinYin" => "YSWJQD",
            "firstPinYin" => "Y",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "IL",
            "chineseName" => "以色列",
            "englishName" => "Israel",
            "nativeName" => "Middle East",
            "nationalityCode" => "ISR",
            "phoneCode" => "972",
            "fullPinYin" => "YiSeLie",
            "simplePinYin" => "YSL",
            "firstPinYin" => "Y",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "IQ",
            "chineseName" => "伊拉克",
            "englishName" => "Iraq",
            "nativeName" => "Middle East",
            "nationalityCode" => "IRQ",
            "phoneCode" => "964",
            "fullPinYin" => "YiLaKe",
            "simplePinYin" => "YLK",
            "firstPinYin" => "Y",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "IR",
            "chineseName" => "伊朗伊斯兰共和国",
            "englishName" => "Iran Islamic Republic of",
            "nativeName" => "Middle East",
            "nationalityCode" => "IRN",
            "phoneCode" => "98",
            "fullPinYin" => "YiLangYiSiLanGongHeGuo",
            "simplePinYin" => "YLYSLGHG",
            "firstPinYin" => "Y",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "JO",
            "chineseName" => "约旦",
            "englishName" => "Jordan",
            "nativeName" => "Middle East",
            "nationalityCode" => "JOR",
            "phoneCode" => "962",
            "fullPinYin" => "YaoDan",
            "simplePinYin" => "YD",
            "firstPinYin" => "Y",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "YE",
            "chineseName" => "也门",
            "englishName" => "Yemen",
            "nativeName" => "Middle East",
            "nationalityCode" => "YEM",
            "phoneCode" => "967",
            "fullPinYin" => "YeMen",
            "simplePinYin" => "YM",
            "firstPinYin" => "Y",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "ZM",
            "chineseName" => "赞比亚",
            "englishName" => "Zambia",
            "nativeName" => "Africa",
            "nationalityCode" => "ZMB",
            "phoneCode" => "260",
            "fullPinYin" => "ZanBiYa",
            "simplePinYin" => "ZBY",
            "firstPinYin" => "Z",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "CF",
            "chineseName" => "中非共和国",
            "englishName" => "Central African Republic",
            "nativeName" => "Africa",
            "nationalityCode" => "CAF",
            "phoneCode" => "236",
            "fullPinYin" => "ZhongFeiGongHeGuo",
            "simplePinYin" => "ZFGHG",
            "firstPinYin" => "Z",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "TD",
            "chineseName" => "乍得",
            "englishName" => "Chad",
            "nativeName" => "Africa",
            "nationalityCode" => "TCD",
            "phoneCode" => "235",
            "fullPinYin" => "ZhaDe",
            "simplePinYin" => "ZD",
            "firstPinYin" => "Z",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "CN",
            "chineseName" => "中国",
            "englishName" => "China",
            "nativeName" => "North Asia",
            "nationalityCode" => "CHN",
            "phoneCode" => "86",
            "fullPinYin" => "ZhongGuo",
            "simplePinYin" => "ZG",
            "firstPinYin" => "Z",
            "isHot" => 1,
        ),
        array(
            "countryCode" => "HK",
            "chineseName" => "中国香港特别行政区",
            "englishName" => "Hong Kong (sar) China",
            "nativeName" => "North Asia",
            "nationalityCode" => "HKG",
            "phoneCode" => "852",
            "fullPinYin" => "ZhongGuoXiangGangTeBieHangZhengOu",
            "simplePinYin" => "ZGXGTBHZO",
            "firstPinYin" => "Z",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "GI",
            "chineseName" => "直布罗陀",
            "englishName" => "Gibraltar",
            "nativeName" => "South America",
            "nationalityCode" => "GIB",
            "phoneCode" => "350",
            "fullPinYin" => "ZhiBuLuoTuo",
            "simplePinYin" => "ZBLT",
            "firstPinYin" => "Z",
            "isHot" => 0,
        ),
        array(
            "countryCode" => "CL",
            "chineseName" => "智利",
            "englishName" => "Chile",
            "nativeName" => "South America",
            "nationalityCode" => "CHL",
            "phoneCode" => "56",
            "fullPinYin" => "ZhiLi",
            "simplePinYin" => "ZL",
            "firstPinYin" => "Z",
            "isHot" => 0,
        ),
    );
    return $list;
  }
}
// ------------------------------------------------------------------------


